// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATDMAxhhG83wEeE_G5vLIitCOezSPHLkI',
    appId: '1:861975057677:web:844feacc892de71c678c44',
    messagingSenderId: '861975057677',
    projectId: 'project1-3828a',
    authDomain: 'project1-3828a.firebaseapp.com',
    storageBucket: 'project1-3828a.appspot.com',
    measurementId: 'G-ZGRNJ28T11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIjGgZ_SZLZAjZbpfkrc0KFrXv0025YdY',
    appId: '1:861975057677:android:9a25e244f816ad24678c44',
    messagingSenderId: '861975057677',
    projectId: 'project1-3828a',
    storageBucket: 'project1-3828a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN0lEf9BUmX-Z86Hec-hRc3dOk7CIOMJ4',
    appId: '1:861975057677:ios:aa37f3af4b9f914b678c44',
    messagingSenderId: '861975057677',
    projectId: 'project1-3828a',
    storageBucket: 'project1-3828a.appspot.com',
    iosBundleId: 'com.example.project21',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN0lEf9BUmX-Z86Hec-hRc3dOk7CIOMJ4',
    appId: '1:861975057677:ios:1da6ca753b94633d678c44',
    messagingSenderId: '861975057677',
    projectId: 'project1-3828a',
    storageBucket: 'project1-3828a.appspot.com',
    iosBundleId: 'com.example.project21.RunnerTests',
  );
}
